package com.classforge.generation.relational;

public enum RelationalMappingDiagnosticCode {
    CLASS_IDENTIFIER_REQUIRED, CUSTOM_TYPE_UNSUPPORTED, MULTIPLE_INHERITANCE_UNSUPPORTED,
    SUBCLASS_IDENTIFIER_NOT_ALLOWED, REFLEXIVE_RELATIONSHIP_UNSUPPORTED, UNSUPPORTED_MULTIPLICITY,
    COMPOSITION_OWNER_MULTIPLICITY_INVALID, RELATIONAL_TABLE_NAME_COLLISION,
    RELATIONAL_COLUMN_NAME_COLLISION, RELATIONSHIP_CLASS_NOT_FOUND, GENERALIZATION_CYCLE
}
