package com.classforge.generation.spring.validation;

public enum SpringGenerationDiagnosticCode {
    INVALID_ARTIFACT_NAME, INVALID_BASE_PACKAGE, JAVA_IDENTIFIER_INVALID, JAVA_TYPE_NAME_COLLISION,
    JAVA_FIELD_NAME_COLLISION, JAVA_REPOSITORY_NAME_COLLISION, ENTITY_TABLE_NOT_FOUND,
    ENTITY_PRIMARY_KEY_INVALID, RELATION_OWNER_NOT_FOUND, RELATION_TARGET_NOT_FOUND,
    RELATION_FOREIGN_KEY_NOT_FOUND, RELATION_FOREIGN_KEY_AMBIGUOUS, RELATION_NULLABILITY_INCONSISTENT,
    JOIN_TABLE_NOT_FOUND, JOIN_TABLE_FOREIGN_KEYS_INVALID, INHERITANCE_PARENT_NOT_FOUND,
    INHERITANCE_CYCLE, INHERITANCE_PRIMARY_KEY_JOIN_INVALID, SPRING_MODEL_INVALID
}
