# ${model.artifactName}

Generated by ClassForge. Java ${model.javaVersion}, Spring Boot ${model.springBootVersion}.

<#if api.enabled()>Generation mode: **${api.mode?string}**.

The generated API provides CRUD, list/search/filter/sort/pagination/count endpoints and relation IDs in DTOs.

## API contract artifacts

The project root includes `openapi.yaml` (OpenAPI 3.0.3), `postman_collection.json` (Postman Collection v2.1) and `domain-manifest.json` (ClassForge Domain Manifest schema 1.0). OpenAPI/Postman share the canonical HTTP contract; the Domain Manifest adds stable source UUIDs, identifiers, relations, inheritance, capabilities and Auth metadata for generated clients.
</#if><#if api.authEnabled()>## Authentication

Authentication is enabled. `/api/auth/login` accepts `username` and `password`. `/api/auth/bootstrap` is a one-time public bootstrap endpoint that only works while the selected authentication table is empty; it accepts the generated `${api.authEntity().className}Request` body, hashes the selected password field with BCrypt and returns a JWT.

All other `/api/**` routes require `Authorization: Bearer <token>`. Tokens expire after 3600 seconds. Set `JWT_SECRET` to a strong deployment secret before production; the built-in default exists only so the generated project can start locally and in tests.
</#if>
## Java requirement

This project targets JDK ${model.javaVersion} through Gradle Toolchains. Your default system Java may be newer, but Gradle must be able to locate a JDK ${model.javaVersion} installation.

Check detected toolchains with:

- Windows: `gradlew.bat -q javaToolchains`
- Linux/macOS: `./gradlew -q javaToolchains`

## Run

H2 is the default database. Run `./gradlew bootRun` or `gradlew.bat bootRun` on Windows.

For PostgreSQL use `--spring.profiles.active=postgres` and set DB_URL, DB_USERNAME and DB_PASSWORD.
