# ${model.artifactName}

Generated by ClassForge. Java ${model.javaVersion}, Spring Boot ${model.springBootVersion}.

<#if api.enabled()>Generation mode: **${api.mode?string}**.

The generated API provides CRUD, list/search/filter/sort/pagination/count endpoints and relation IDs in DTOs.

## API contract artifacts

The project root includes `openapi.yaml` (OpenAPI 3.0.3), `postman_collection.json` (Postman Collection v2.1) and `domain-manifest.json` (ClassForge Domain Manifest schema 1.0). OpenAPI/Postman share the canonical HTTP contract; the Domain Manifest adds stable source UUIDs, identifiers, relations, inheritance, capabilities and Auth metadata for generated clients.

## Angular frontend

The same ZIP includes `frontend/`, a standalone Angular application with a dashboard and entity-specific list/detail/form components. Its API contract matches this backend and its primary interface color is selected at export time.

Run it with:

```bash
cd frontend
npm install
npm start
```

The development proxy forwards `/api` to `http://localhost:8080`.

## Flutter mobile

The same ZIP also includes `mobile/`, a standalone Flutter application generated from the same Domain Manifest/API contract. Android is the formally accepted target and the Android emulator uses `http://10.0.2.2:8080` for the backend.

Run it with:

```bash
cd mobile
flutter pub get
flutter run
```

Validate it with `flutter analyze`, `flutter test` and `flutter build apk --debug`.

## Assistant: chat and voice

The generated Spring backend exposes `/api/assistant/plan`, `/api/assistant/voice` and `/api/assistant/apply`. Angular and Flutter only call these Spring endpoints. Spring reuses the same local ClassForge-style runtimes by default: llama.cpp/Qwen at `http://127.0.0.1:8092` and whisper.cpp at `http://127.0.0.1:8093`.

Text and Whisper transcripts converge on the same native-tool planner. Read operations execute immediately. CREATE, UPDATE, relation changes and DELETE return a sanitized preview plus an opaque, short-lived token; only `/api/assistant/apply` executes that pending mutation. Sensitive values such as passwords are masked in previews.

Runtime overrides are available through `LLAMA_URL`, `LLAMA_MODEL`, `WHISPER_URL`, `WHISPER_LANGUAGE` and `APP_API_BASE_URL`. `APP_API_BASE_URL` must point to this generated Spring API when it does not run on port 8080.
</#if><#if api.authEnabled()>## Authentication

Authentication is enabled. `/api/auth/login` accepts `username` and `password`. `/api/auth/bootstrap` is a one-time public bootstrap endpoint that only works while the selected authentication table is empty; it accepts the generated `${api.authEntity().className}Request` body, hashes the selected password field with BCrypt and returns a JWT.

All other `/api/**` routes require `Authorization: Bearer <token>`. Tokens expire after 3600 seconds. Set `JWT_SECRET` to a strong deployment secret before production; the built-in default exists only so the generated project can start locally and in tests.
</#if>
## Java requirement

This project targets JDK ${model.javaVersion} through Gradle Toolchains. Your default system Java may be newer, but Gradle must be able to locate a JDK ${model.javaVersion} installation.

Check detected toolchains with:

- Windows: `gradlew.bat -q javaToolchains`
- Linux/macOS: `./gradlew -q javaToolchains`

## Run

H2 is the default database. Run `./gradlew bootRun` or `gradlew.bat bootRun` on Windows.

For PostgreSQL use `--spring.profiles.active=postgres` and set DB_URL, DB_USERNAME and DB_PASSWORD.
