# ${model.artifactName}

Generated by ClassForge. Java ${model.javaVersion}, Spring Boot ${model.springBootVersion}.

H2 is the default database. Run `./gradlew bootRun` or `gradlew.bat bootRun` on Windows.

For PostgreSQL use `--spring.profiles.active=postgres` and set DB_URL, DB_USERNAME and DB_PASSWORD.
