package com.classforge.assistant;

public enum AssistantActionType {
    CREATE_CLASS,
    CREATE_ASSOCIATION_CLASS,
    RENAME_CLASS,
    DELETE_CLASS,
    ADD_ATTRIBUTES,
    UPDATE_ATTRIBUTE,
    DELETE_ATTRIBUTE,
    CREATE_RELATIONSHIP,
    UPDATE_RELATIONSHIP,
    DELETE_RELATIONSHIP
}